Forum/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import SignupView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
]

Forum/forum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("forum.urls")),
    path('accounts/', include("accounts.urls")),
]

Forum/accounts/models.py
from django.db import models

# Create your models here.

Forum/forum/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Forum(models.Model):
    title = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.title)+"-year:"+str(self.created_at.year)+"-month:"+str(self.created_at.month)+"-day:"+str(self.created_at.day)

class Comment(models.Model):
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    text = models.TextField()
    #response = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.user)+"-year:"+str(self.created_at.year)+"-month:"+str(self.created_at.month)+"-day:"+str(self.created_at.day)

Forum/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)

Forum/forum/forms.py
import os
from django import forms

class My_chat_botForm(forms.Form):
    text = forms.CharField(label='テキスト', max_length=50)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['text'].widget.attrs['class'] = 'form-control'
        self.fields['text'].widget.attrs['placeholder'] = 'テキストをここに入力してください。'

    def send_message(self):
        text = self.cleaned_data['text']
        return text

Forum/accounts/views.py
from django.shortcuts import render
# Create your views here.

from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import SignupForm

class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("index")

Forum/forum/views.py
from django.shortcuts import render

from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    FormView
    )
from .forms import My_chat_botForm
from .models import Forum, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from .my_chat_bot import MyChatBot
from django.core import serializers
# Create your views here.


class ForumDetailView(LoginRequiredMixin, FormView):
    template_name = 'forum/forum_detail.html'
    form_class = My_chat_botForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Forum"] = Forum.objects.get(id=self.kwargs['pk'])
        context["Comment_List"] = Comment.objects.filter(forum_id=self.kwargs['pk'])
        return context
    
    def get_success_url(self):
        return reverse('forum-detail', kwargs={'pk':self.kwargs['pk']})

    def form_valid(self, form):
        message = form.send_message()
        #response = MyChatBot("名無し:", message)
        comment = Comment(user=self.request.user, text=message, forum=Forum.objects.get(id=self.kwargs['pk']))
        comment.save()
        data = serializers.serialize('json', [comment])
        return super().form_valid(form)

    

    
class ForumListView(LoginRequiredMixin, ListView):
    template_name = "forum/forum_list.html"
    model = Forum

class ForumCreateView(LoginRequiredMixin, CreateView):
    template_name = "forum/forum_create.html"
    model = Forum
    success_url = reverse_lazy("forum-list")
    fields = ("title",)
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

Forum/forum/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'forum/css/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-dark bg-success sticky-top">
        <div class="navbar-nav d-flex flex-row">
            <a class="nav-link mx-3" href="{% url 'forum-list' %}">掲示板一覧へ</a>
            <a class="nav-link mx-3" href="{% url 'forum-create' %}">掲示板作成へ</a>
        </div>
        <div class="navbar-nav d-flex flex-row">
            {% if request.user.is_authenticated %}
            <a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>

            {% else %}
            <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
            <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">ユーザー登録</a>
            {% endif %}
        </div>
    </nav>
    <div class="p-4">
        <h1>{% block h1 %}{% endblock h1 %}</h1>
        {% block content %}{% endblock content %}
    </div>
</body>

</html>

Forum/forum/templates/forum/forum_create.html
{%extends 'base.html'%}

{%block title%}掲示板作成{%endblock title%}

{%block content%}
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="作成">
</form>
{% endblock content %}

Forum/forum/templates/forum/forum_detail.html
{% extends 'base.html' %}

{% block title %}{{ Forum.title }}{% endblock title %}
{% block h1 %}{{ Forum.title }}{% endblock h1 %}

{% block content %}
<div class="p-4 m-4 bg-light border border-success rounded">
    <h2 class="text-success">{{Forum.title}} : {{Forum.created_at.year}}年 {{Forum.created_at.month}}月 {{Forum.created_at.day}}日</h2>
    <div class="border p-4 mb-2">
        <div>
            <div class="px-2">
                <p>----------------------</p>
                {% for comment in Comment_List %}
                <p>{{comment.user.username}}:{{comment.text}}</p>
                <p></p>
                <span>({{comment.created_at.year}}年 {{comment.created_at.month}}月
                {{comment.created_at.day}}日 {{comment.created_at.hour}}:{{comment.created_at.minute}})</span>
                <p>----------------------</p>
                <!--
                <p>{{comment.response}}</p>
                <p></p>
                <span>({{comment.created_at.year}}年 {{comment.created_at.month}}月
                    {{comment.created_at.day}}日 {{comment.created_at.hour}}:{{comment.created_at.minute}})</span>
                <p>----------------------</p>
                -->
                {% endfor %}
            </div>
        </div>
    </div>
    <!--投稿-->
    <div class="ui segment">
        <form class="ui-form" action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="ui button orange" type="submit">投稿</button>
        </form>
    </div>
    <a href="{% url 'forum-list' %}" class="btn btn-primary">一覧へ</a>
</div>
{% endblock content %}

Forum/forum/templates/forum/forum_list.html
{% extends 'base.html' %}

{% block title %}掲示板一覧{% endblock title %}
{% block h1 %}掲示板一覧{% endblock h1 %}

{% block content %}
<div class="col-9">
    {% for item in object_list %}
    <div class="p-4 m-4 bg-light border border-success rounded">
        <h2 class="text-success">{{item.title}}</h2>
        <a href="{% url 'forum-detail' item.pk %}">中身へ</a>
    </div>
</div>
{% endfor %}
{% endblock content %}